from html import escape
from pathlib import Path

import streamlit as st

from backend.backend_utils.application_utils import create_hospital_application
from backend.supabase_client import admin_supabase
from backend.auth import auth_email_exists


PROJECT_ROOT = Path(__file__).resolve().parents[2]

APPLICATION_CSS_PATH = (
    PROJECT_ROOT
    / "shared"
    / "theme"
    / "css_content"
    / "application.css"
)


# ============================================================
# APPLICATION INTRODUCTION
# ============================================================

INTRO_WELCOME = 1
INTRO_LUNGSIGHT = 2


# ============================================================
# STEPS
# ============================================================

APPLICATION_STEPS = [
    ("Hospital", "Hospital Information"),
    ("Representative", "Authorized Representative"),
    ("Plan", "Selected Subscription"),
    ("Administrator", "Hospital Administrator"),
    ("Agreement", "Service Agreement"),
    ("Review", "Review & Submit"),
    ("Payment", "Payment"),
]


HOSPITAL_TYPES = [
    "Government Hospital",
    "Private Hospital",
    "Medical Center",
    "Other",
]


AGREEMENT_TEXT = """
**LungSight Hospital Service Agreement**

By submitting this application and selecting the agreement checkbox, the
hospital and its authorized representative acknowledge and agree to the
following terms:

### 1. Purpose of LungSight

LungSight is a healthcare decision-support system designed to assist
healthcare professionals in reviewing chest X-ray examinations and
organizing related clinical information.

LungSight may provide AI-assisted findings that may be associated with
**presumptive pneumonia**. These results are intended to support, and not
replace, professional clinical assessment.

LungSight does not independently establish a final diagnosis, prescribe
treatment, or replace the judgment of a qualified physician or other
authorized healthcare professional.

### 2. Clinical Review and Responsibility

All AI-assisted results generated by LungSight must be reviewed and
interpreted by an appropriately qualified healthcare professional.

The hospital and its authorized healthcare professionals remain responsible
for clinical decisions, including diagnosis, treatment, referral, follow-up,
and other patient-care decisions.

LungSight results should be considered supportive information and must not
be used as the sole basis for making a clinical decision.

### 3. Patient Information and Data Privacy

The hospital is responsible for ensuring that patient information submitted
to LungSight is collected, used, stored, and processed in accordance with
applicable laws, regulations, hospital policies, and privacy requirements.

Patient information may include personal information and sensitive personal
information, including health and medical information.

The hospital agrees to provide only information that is necessary for the
intended clinical and operational purposes of the system and to ensure that
its personnel are authorized to access and process such information.

The hospital is responsible for maintaining appropriate confidentiality
when handling patient records, medical information, and uploaded chest
X-ray images.

### 4. Chest X-ray Images

Chest X-ray images submitted to LungSight must belong to or be lawfully
accessible by the hospital for the intended clinical purpose.

Where applicable, the hospital should remove unnecessary identifying
information from X-ray images before uploading them to the system.

The hospital must not upload images or information that it is not legally
authorized to process.

### 5. User Accounts and Access

Each hospital user must use their assigned account and must not share
account credentials with another person.

Hospital administrators are responsible for managing authorized users
within their organization and for promptly addressing unauthorized or
inappropriate account access.

Users must maintain the confidentiality of their passwords and other
authentication information.

The hospital is responsible for notifying the LungSight administrator of
suspected unauthorized access or other security incidents involving its
accounts.

### 6. Subscription Plan and Usage Limits

The hospital's access to LungSight is based on the subscription plan
selected during the application process.

The selected plan determines the applicable limits for hospital users,
patient records, and chest X-ray analysis requests.

The hospital agrees not to intentionally circumvent, bypass, or manipulate
these subscription limits.

Additional usage or changes to the subscription may be subject to the
available plans, system policies, and approval by the LungSight
administrator.

### 7. System Availability and Technical Limitations

LungSight is provided as a software-based decision-support system.
AI-assisted results may be affected by image quality, available patient
information, system limitations, or other technical factors.

The hospital acknowledges that no automated analysis system should be
considered infallible and that professional review remains necessary.

LungSight may undergo maintenance, updates, improvements, or temporary
service interruptions as necessary for system operation and development.

### 8. Prohibited Use

The hospital and its users must not:

- Use LungSight for purposes unrelated to authorized healthcare,
  administrative, or system functions.
- Attempt to gain unauthorized access to another user's account or
  information.
- Upload information that the hospital is not authorized to process.
- Intentionally misuse, modify, disrupt, or interfere with the system.
- Attempt to bypass security controls, subscription limits, or access
  restrictions.
- Use LungSight's AI-assisted results as a substitute for required
  professional clinical evaluation.

### 9. Hospital Responsibility

The hospital is responsible for the accuracy of information entered by its
authorized personnel and for ensuring that its users receive appropriate
training regarding the responsible use of LungSight.

The hospital must maintain appropriate internal procedures for protecting
patient information and controlling access to the system.

### 10. Application Review and Approval

Submission of this application does not automatically create a LungSight
hospital account.

Applications are subject to review and approval by the authorized
LungSight system administrator.

The selected subscription and requested hospital access become effective
only after the application has been reviewed and approved in accordance
with LungSight's applicable procedures.

### 11. Agreement Changes

LungSight may update this Service Agreement when necessary to reflect
changes to the system, services, security requirements, applicable
policies, or legal and regulatory requirements.

Where appropriate, hospitals may be notified of material changes before
they become applicable.

### 12. Acknowledgment

By selecting "I have read and agree to the LungSight Service Agreement,"
the authorized representative confirms that they have read and understood
these terms and that they are authorized to submit this application on
behalf of the hospital.

The representative further acknowledges that the hospital will be
responsible for ensuring that its authorized users comply with these terms
when using LungSight.
"""


# ============================================================
# SMALL HELPERS
# ============================================================

def load_application_css():
    if APPLICATION_CSS_PATH.exists():
        css = APPLICATION_CSS_PATH.read_text(encoding="utf-8")
        st.markdown(
            f"<style>{css}</style>",
            unsafe_allow_html=True,
        )


def safe(value):
    """
    Escape text before inserting it into HTML.
    Empty values display as an em dash.
    """
    text = escape(str(value or "").strip())
    return text or "—"


def peso(amount):
    """
    Format a number as Philippine peso.

    Example:
        1500 -> ₱1,500.00
    """
    return f"₱{float(amount or 0):,.2f}"


def limit_text(value):
    """
    None means there is no database limit.
    """
    if value is None:
        return "Unlimited"

    return f"{value:,}"


def full_name(person):
    parts = [
        person.get("first_name"),
        person.get("middle_name"),
        person.get("last_name"),
    ]

    return " ".join(
        part
        for part in parts
        if part
    )


def is_valid_email(email):
    name, _, domain = email.partition("@")

    return (
        bool(name)
        and "." in domain
        and " " not in email
    )


def find_missing(required):
    """
    required looks like:
        {"Field label": value}

    Returns labels for empty values.
    """
    return [
        label
        for label, value in required.items()
        if not value.strip()
    ]


def get_amount(subscription):
    if subscription.get("billing_cycle") == "Yearly":
        return float(
            subscription.get("price_yearly") or 0
        )

    return float(
        subscription.get("price_monthly") or 0
    )


def go_to_step(step):
    st.session_state.client_application_step = step
    st.rerun()


def rows_html(rows):
    """
    Create label/value rows for review and payment summaries.
    """

    items = "".join(
        f"<div class='ls-row'>"
        f"<span>{label}</span>"
        f"<b>{safe(value)}</b>"
        f"</div>"
        for label, value in rows
    )

    return (
        f"<div class='ls-rows'>"
        f"{items}"
        f"</div>"
    )


def limits_html(subscription):
    """
    Display the three primary subscription limits.
    """

    limits = [
        (
            "Users",
            limit_text(
                subscription.get("max_users")
            ),
        ),
        (
            "Patients",
            limit_text(
                subscription.get("max_patients")
            ),
        ),
        (
            "X-rays per month",
            limit_text(
                subscription.get(
                    "max_xrays_per_month"
                )
            ),
        ),
    ]

    items = "".join(
        f"<div class='ls-limit'>"
        f"<b>{value}</b>"
        f"<span>{label}</span>"
        f"</div>"
        for label, value in limits
    )

    return (
        f"<div class='ls-limits'>"
        f"{items}"
        f"</div>"
    )


def note(text, kind=""):
    """
    Display a small styled message box.
    """

    st.markdown(
        f"<div class='ls-note ls-note-{kind}'>"
        f"{text}"
        f"</div>",
        unsafe_allow_html=True,
    )


def step_header(
    title,
    caption,
    required=False,
):
    required_text = (
        "<span class='ls-required'>* Required</span>"
        if required
        else ""
    )

    st.markdown(
        "<div class='ls-step-header'>"
        "<div>"
        f"<p class='ls-step-title'>{title}</p>"
        f"<p class='ls-step-caption'>{caption}</p>"
        "</div>"
        f"{required_text}"
        "</div>",
        unsafe_allow_html=True,
    )


def name_fields(data):
    """
    First, middle, and last name fields.
    """

    first_col, middle_col, last_col = st.columns(3)

    first_name = first_col.text_input(
        "First name *",
        value=data.get(
            "first_name",
            "",
        ),
    )

    middle_name = middle_col.text_input(
        "Middle name",
        value=data.get(
            "middle_name",
            "",
        ),
    )

    last_name = last_col.text_input(
        "Last name *",
        value=data.get(
            "last_name",
            "",
        ),
    )

    return (
        first_name,
        middle_name,
        last_name,
    )


def form_nav_buttons():
    """
    Back and Next buttons for forms.
    """

    back_col, next_col = st.columns(2)

    back = back_col.form_submit_button(
        "Back",
        width="stretch",
    )

    go_next = next_col.form_submit_button(
        "Next",
        type="primary",
        width="stretch",
    )

    return (
        back,
        go_next,
    )


def nav_buttons(
    key,
    back_step,
    next_label="Next",
):
    """
    Navigation buttons for non-form steps.
    """

    back_col, next_col = st.columns(2)

    if back_col.button(
        "Back",
        key=f"{key}_back",
        width="stretch",
    ):
        go_to_step(back_step)

    return next_col.button(
        next_label,
        key=f"{key}_next",
        type="primary",
        width="stretch",
    )


# ============================================================
# APPLICATION INTRODUCTION
# ============================================================

def render_intro_welcome():
    """
    Introduction page 1.

    Introduces LungSight before the applicant
    begins providing hospital information.
    """

    st.markdown(
        "<div class='ls-intro-page'>"
        "<div class='ls-intro-icon'>"
        "<span class='material-symbols-rounded'>radiology</span>"
        "</div>"
        "<p class='ls-intro-kicker'>WELCOME TO LUNGSIGHT</p>"
        "<p class='ls-intro-title'>"
        "A smarter way to support chest X-ray screening."
        "</p>"
        "<p class='ls-intro-text'>"
        "LungSight is a healthcare decision-support system designed to "
        "assist hospitals in reviewing chest X-rays and organizing the "
        "clinical workflow around patients who may require further "
        "evaluation."
        "</p>"
        "<p class='ls-intro-text'>"
        "By bringing chest X-ray analysis, patient information, physician "
        "review, and follow-up workflows into one system, LungSight helps "
        "healthcare teams work with important clinical information more "
        "efficiently while keeping professional judgment at the center "
        "of every decision."
        "</p>"
        "<div class='ls-intro-highlights'>"
        "<div class='ls-intro-highlight'>"
        "<div class='ls-intro-highlight-icon'>"
        "<span class='material-symbols-rounded'>radiology</span>"
        "</div>"
        "<div>"
        "<span class='ls-intro-highlight-title'>"
        "Chest X-ray support"
        "</span>"
        "<span class='ls-intro-highlight-text'>"
        "AI-assisted analysis can help identify chest X-ray findings "
        "that may require further clinical assessment."
        "</span>"
        "</div>"
        "</div>"
        "<div class='ls-intro-highlight'>"
        "<div class='ls-intro-highlight-icon'>"
        "<span class='material-symbols-rounded'>account_tree</span>"
        "</div>"
        "<div>"
        "<span class='ls-intro-highlight-title'>"
        "Connected clinical workflow"
        "</span>"
        "<span class='ls-intro-highlight-text'>"
        "Connect patient information, examinations, physician review, "
        "and follow-up activities within one organized workspace."
        "</span>"
        "</div>"
        "</div>"
        "<div class='ls-intro-highlight'>"
        "<div class='ls-intro-highlight-icon'>"
        "<span class='material-symbols-rounded'>medical_services</span>"
        "</div>"
        "<div>"
        "<span class='ls-intro-highlight-title'>"
        "Built for healthcare teams"
        "</span>"
        "<span class='ls-intro-highlight-text'>"
        "Support hospital staff while keeping clinical decisions "
        "with qualified healthcare professionals."
        "</span>"
        "</div>"
        "</div>"
        "</div>"
        "</div>",
        unsafe_allow_html=True,
    )

    st.markdown(
        "<div class='ls-intro-note'>"
        "<div class='ls-intro-note-icon'>"
        "<span class='material-symbols-rounded'>verified</span>"
        "</div>"
        "<div>"
        "<strong>Clinical decision support</strong>"
        "<span>"
        "LungSight is intended to assist healthcare professionals. "
        "It does not replace professional medical judgment, diagnosis, "
        "or physician review."
        "</span>"
        "</div>"
        "</div>",
        unsafe_allow_html=True,
    )

    if st.button(
        "Continue",
        key="intro_page_one_continue",
        type="primary",
        width="stretch",
    ):
        st.session_state.application_intro_page = 2
        st.rerun()

def render_intro_lungsight():
    """
    Introduction page 2.

    Explains LungSight's clinical purpose and
    dynamically describes the selected subscription plan.
    """

    subscription = st.session_state.client_application["subscription"]

    plan_name = safe(subscription.get("plan_name"))

    max_users = limit_text(subscription.get("max_users"))
    max_patients = limit_text(subscription.get("max_patients"))
    max_xrays = limit_text(subscription.get("max_xrays_per_month"))

    monthly = float(subscription.get("price_monthly") or 0)
    yearly = float(subscription.get("price_yearly") or 0)

    st.markdown(
        "<div class='ls-intro-page ls-intro-clinical-page'>"
        "<div class='ls-intro-icon'>"
        "<span class='material-symbols-rounded'>pulmonology</span>"
        "</div>"
        "<p class='ls-intro-kicker'>"
        "LUNGSIGHT CLINICAL SUPPORT"
        "</p>"
        "<p class='ls-intro-title'>"
        "Supporting the detection of presumptive pneumonia."
        "</p>"
        "<p class='ls-intro-text'>"
        "LungSight can assist healthcare professionals by analyzing "
        "chest X-rays for findings that may be associated with "
        "presumptive pneumonia. The system provides AI-assisted "
        "results to support further clinical assessment and physician "
        "review."
        "</p>"
        "<p class='ls-intro-text'>"
        "The LungSight workflow is designed so that AI-assisted "
        "analysis is followed by professional evaluation. Physicians "
        "can review the available patient information and imaging "
        "results before making the final clinical decision."
        "</p>"
        "<div class='ls-intro-clinical-flow'>"
        "<div class='ls-intro-flow-item'>"
        "<div class='ls-intro-flow-icon'>"
        "<span class='material-symbols-rounded'>image_search</span>"
        "</div>"
        "<span class='ls-intro-flow-number'>01</span>"
        "<span class='ls-intro-flow-title'>"
        "Chest X-ray analysis"
        "</span>"
        "<span class='ls-intro-flow-text'>"
        "LungSight analyzes the uploaded chest X-ray and provides "
        "an AI-assisted assessment of findings that may require "
        "further evaluation."
        "</span>"
        "</div>"
        "<div class='ls-intro-flow-item'>"
        "<div class='ls-intro-flow-icon'>"
        "<span class='material-symbols-rounded'>clinical_notes</span>"
        "</div>"
        "<span class='ls-intro-flow-number'>02</span>"
        "<span class='ls-intro-flow-title'>"
        "Physician review"
        "</span>"
        "<span class='ls-intro-flow-text'>"
        "The result can be reviewed by a qualified healthcare "
        "professional alongside the patient's clinical information."
        "</span>"
        "</div>"
        "<div class='ls-intro-flow-item'>"
        "<div class='ls-intro-flow-icon'>"
        "<span class='material-symbols-rounded'>health_and_safety</span>"
        "</div>"
        "<span class='ls-intro-flow-number'>03</span>"
        "<span class='ls-intro-flow-title'>"
        "Clinical decision"
        "</span>"
        "<span class='ls-intro-flow-text'>"
        "The physician determines the appropriate diagnosis, "
        "management, and follow-up based on the complete clinical "
        "assessment."
        "</span>"
        "</div>"
        "</div>"
        "</div>",
        unsafe_allow_html=True,
    )

    st.markdown(
        "<div class='ls-selected-plan-intro'>"
        "<div class='ls-selected-plan-icon'>"
        "<span class='material-symbols-rounded'>workspace_premium</span>"
        "</div>"
        "<p class='ls-selected-plan-kicker'>"
        "YOUR SELECTED PLAN"
        "</p>"
        f"<p class='ls-selected-plan-name'>{plan_name}</p>"
        "<p class='ls-selected-plan-description'>"
        f"Your selected {plan_name} subscription provides your hospital "
        f"with access for up to <strong>{max_users}</strong> user(s), "
        f"supports up to <strong>{max_patients}</strong> patient "
        f"record(s), and allows up to <strong>{max_xrays}</strong> "
        "chest X-ray analysis request(s) per month."
        "</p>"
        "<div class='ls-selected-plan-limits'>"
        f"<div>"
        f"<span class='material-symbols-rounded'>group</span>"
        f"<strong>{max_users}</strong>"
        f"<span>Users</span>"
        f"</div>"
        f"<div>"
        f"<span class='material-symbols-rounded'>groups</span>"
        f"<strong>{max_patients}</strong>"
        f"<span>Patients</span>"
        f"</div>"
        f"<div>"
        f"<span class='material-symbols-rounded'>radiology</span>"
        f"<strong>{max_xrays}</strong>"
        f"<span>X-rays / month</span>"
        f"</div>"
        "</div>"
        f"<p class='ls-selected-plan-price'>"
        f"{peso(monthly)} <span>/ month</span>"
        f"</p>"
        f"<p class='ls-selected-plan-yearly'>"
        f"Annual billing: {peso(yearly)} per year"
        f"</p>"
        "</div>",
        unsafe_allow_html=True,
    )

    note(
        "You can review and confirm your billing cycle again during the "
        "application process. Your subscription will be subject to approval "
        "by the LungSight system administrator."
    )

    back_col, continue_col = st.columns(2)

    if back_col.button(
        "Back",
        key="intro_page_two_back",
        width="stretch",
    ):
        st.session_state.application_intro_page = 1
        st.rerun()

    if continue_col.button(
        "Continue to application",
        key="intro_page_two_continue",
        type="primary",
        width="stretch",
    ):
        st.session_state.application_intro_page = 0
        st.session_state.client_application_step = 0
        st.rerun()


def render_application_introduction():
    """
    Controls the two-page LungSight introduction.

    Returns True while the introduction is active.
    """

    intro_page = st.session_state.get(
        "application_intro_page",
        INTRO_WELCOME,
    )

    if intro_page == INTRO_WELCOME:
        render_intro_welcome()
        return True

    if intro_page == INTRO_LUNGSIGHT:
        render_intro_lungsight()
        return True

    return False


# ============================================================
# INITIALIZE / CLEAR
# ============================================================

def initialize_application(plan):

    current_plan_id = plan.get("plan_id")

    existing_application = st.session_state.get(
        "client_application"
    )

    existing_plan_id = None

    if existing_application:
        existing_plan_id = (
            existing_application
            .get("subscription", {})
            .get("plan_id")
        )

    # Start a new application when none exists
    # or a different plan was chosen.
    if (
        existing_application is None
        or existing_plan_id != current_plan_id
    ):

        st.session_state.client_application = {
            "hospital": {},
            "representative": {},
            "subscription": {
                "plan_id": plan.get("plan_id"),
                "plan_name": plan.get("plan_name"),
                "price_monthly": plan.get(
                    "price_monthly"
                ),
                "price_yearly": plan.get(
                    "price_yearly"
                ),
                "max_users": plan.get(
                    "max_users"
                ),
                "max_patients": plan.get(
                    "max_patients"
                ),
                "max_xrays_per_month": plan.get(
                    "max_xrays_per_month"
                ),
                "billing_cycle": "Monthly",
            },
            "administrator": {},
            "agreement": {},
        }

        st.session_state.application_intro_page = (
            INTRO_WELCOME
        )

        st.session_state.client_application_step = 0

    if "client_application_step" not in st.session_state:
        st.session_state.client_application_step = 0

    if "application_intro_page" not in st.session_state:
        st.session_state.application_intro_page = (
            INTRO_WELCOME
        )

    # Clear leftover payment state on a fresh application.
    if existing_application is None:

        for key in (
            "application_id",
            "checkout_url",
            "payment_success",
        ):
            st.session_state.pop(
                key,
                None,
            )


def clear_application():

    keys_to_clear = (
        "client_application",
        "client_application_step",
        "application_intro_page",
        "selected_plan",
        "show_application_form",
        "application_submitted",
        "application_billing_cycle",
        "application_id",
        "checkout_url",
        "payment_success",
    )

    for key in keys_to_clear:
        st.session_state.pop(
            key,
            None,
        )


# ============================================================
# PROGRESS TRACKER
# ============================================================

def render_progress():

    current = (
        st.session_state.client_application_step
    )

    total = len(APPLICATION_STEPS)

    percent = round(
        current / total * 100
    )

    if current + 1 < total:
        up_next = (
            f"Next: "
            f"{APPLICATION_STEPS[current + 1][1]}"
        )
    else:
        up_next = "Last step"

    steps_html = ""

    for number, (
        short_name,
        _,
    ) in enumerate(APPLICATION_STEPS):

        if number < current:
            state = "done"
            mark = "✓"

        elif number == current:
            state = "current"
            mark = number + 1

        else:
            state = "todo"
            mark = number + 1

        steps_html += (
            f"<div class='ls-step ls-step-{state}'>"
            f"<span class='ls-dot'>{mark}</span>"
            f"<span class='ls-step-name'>{short_name}</span>"
            "</div>"
        )

    st.markdown(
        "<div class='ls-progress'>"
        "<div class='ls-progress-top'>"
        "<div>"
        f"<p class='ls-progress-title'>"
        f"Step {current + 1} of {total}"
        "</p>"
        f"<p class='ls-progress-meta'>{up_next}</p>"
        "</div>"
        f"<div class='ls-progress-percent'>"
        f"{percent}%"
        "<small>complete</small>"
        "</div>"
        "</div>"
        "<div class='ls-bar'>"
        f"<div class='ls-bar-fill' style='width:{percent}%'>"
        "</div>"
        "</div>"
        f"<div class='ls-steps'>{steps_html}</div>"
        "</div>",
        unsafe_allow_html=True,
    )


# ============================================================
# STEP 1 - HOSPITAL INFORMATION
# ============================================================

def render_hospital_information():

    step_header(
        "Hospital information",
        "Provide the official details of the hospital or healthcare facility.",
        required=True,
    )

    errors = st.container()

    data = (
        st.session_state
        .client_application["hospital"]
    )

    current_type = data.get(
        "hospital_type",
        HOSPITAL_TYPES[0],
    )

    if current_type not in HOSPITAL_TYPES:
        current_type = HOSPITAL_TYPES[0]

    with st.form(
        "hospital_information_form"
    ):

        hospital_name = st.text_input(
            "Hospital name *",
            value=data.get(
                "hospital_name",
                "",
            ),
            placeholder="e.g. Mandaue City Hospital",
        )

        type_col, contact_col = st.columns(2)

        hospital_type = type_col.selectbox(
            "Hospital type *",
            HOSPITAL_TYPES,
            index=HOSPITAL_TYPES.index(
                current_type
            ),
        )

        contact_number = contact_col.text_input(
            "Contact number *",
            value=data.get(
                "contact_number",
                "",
            ),
            placeholder="+63 9XX XXX XXXX",
        )

        address = st.text_area(
            "Complete address *",
            value=data.get(
                "address",
                "",
            ),
            placeholder="Street / Barangay / City / Province",
            height=80,
        )

        email_col, website_col = st.columns(2)

        hospital_email = email_col.text_input(
            "Official hospital email *",
            value=data.get(
                "hospital_email",
                "",
            ),
            placeholder="hospital@example.com",
        )

        website = website_col.text_input(
            "Website",
            value=data.get(
                "website",
                "",
            ),
            placeholder="https://example.com",
        )

        submitted = st.form_submit_button(
            "Next",
            type="primary",
            width="stretch",
        )

    if not submitted:
        return

    missing = find_missing(
        {
            "Hospital name": hospital_name,
            "Complete address": address,
            "Contact number": contact_number,
            "Official hospital email": hospital_email,
        }
    )

    if missing:

        errors.error(
            "Please complete: "
            + ", ".join(missing)
            + "."
        )

        return

    hospital_email = (
        hospital_email
        .strip()
        .lower()
    )

    if not is_valid_email(
        hospital_email
    ):

        errors.error(
            "Please enter a valid hospital email address."
        )

        return

    try:

        response = (
            admin_supabase
            .table("hospitals")
            .select("hospital_id")
            .eq(
                "email",
                hospital_email,
            )
            .limit(1)
            .execute()
        )

        if response.data:

            errors.error(
                "This hospital email already exists."
            )

            return

    except Exception as e:

        errors.error(
            f"Unable to verify the hospital email: {e}"
        )

        return

    st.session_state.client_application[
        "hospital"
    ] = {
        "hospital_name": hospital_name.strip(),
        "hospital_type": hospital_type,
        "address": address.strip(),
        "contact_number": contact_number.strip(),
        "hospital_email": hospital_email,
        "website": website.strip(),
    }

    go_to_step(1)


# ============================================================
# STEP 2 - AUTHORIZED REPRESENTATIVE
# ============================================================

def render_authorized_representative():

    step_header(
        "Authorized representative",
        "The person authorized to submit this application for the hospital.",
        required=True,
    )

    errors = st.container()

    data = (
        st.session_state
        .client_application["representative"]
    )

    with st.form(
        "authorized_representative_form"
    ):

        (
            first_name,
            middle_name,
            last_name,
        ) = name_fields(data)

        position = st.text_input(
            "Position / designation *",
            value=data.get(
                "position",
                "",
            ),
            placeholder="e.g. Hospital Director",
        )

        contact_col, email_col = st.columns(2)

        contact_number = contact_col.text_input(
            "Contact number *",
            value=data.get(
                "contact_number",
                "",
            ),
            placeholder="+63 9XX XXX XXXX",
        )

        email = email_col.text_input(
            "Email address *",
            value=data.get(
                "email",
                "",
            ),
            placeholder="representative@hospital.org",
        )

        back, go_next = form_nav_buttons()

    if back:
        go_to_step(0)

    if not go_next:
        return

    missing = find_missing(
        {
            "First name": first_name,
            "Last name": last_name,
            "Position": position,
            "Contact number": contact_number,
            "Email address": email,
        }
    )

    if missing:

        errors.error(
            "Please complete: "
            + ", ".join(missing)
            + "."
        )

        return

    email = (
        email
        .strip()
        .lower()
    )

    if not is_valid_email(email):

        errors.error(
            "Please enter a valid email address."
        )

        return

    st.session_state.client_application[
        "representative"
    ] = {
        "first_name": first_name.strip(),
        "middle_name": middle_name.strip(),
        "last_name": last_name.strip(),
        "position": position.strip(),
        "contact_number": contact_number.strip(),
        "email": email,
    }

    go_to_step(2)


# ============================================================
# STEP 3 - SELECTED SUBSCRIPTION
# ============================================================

def render_subscription_confirmation():

    step_header(
        "Selected subscription",
        "Confirm the plan you chose and how you would like to be billed.",
    )

    subscription = (
        st.session_state
        .client_application["subscription"]
    )

    monthly = float(
        subscription.get(
            "price_monthly"
        ) or 0
    )

    yearly = float(
        subscription.get(
            "price_yearly"
        ) or 0
    )

    with st.container(
        key="plan_summary"
    ):

        st.markdown(
            "<p class='ls-plan-label'>"
            "Your selected plan"
            "</p>"
            f"<p class='ls-plan-name'>"
            f"{safe(subscription.get('plan_name'))}"
            "</p>",
            unsafe_allow_html=True,
        )

        billing_cycle = st.radio(
            "Billing cycle",
            ["Monthly", "Yearly"],
            index=(
                0
                if subscription.get(
                    "billing_cycle"
                ) == "Monthly"
                else 1
            ),
            horizontal=True,
            key="application_billing_cycle",
        )

        subscription[
            "billing_cycle"
        ] = billing_cycle

        if billing_cycle == "Yearly":
            price = yearly
            period = "year"
        else:
            price = monthly
            period = "month"

        st.markdown(
            f"<p class='ls-plan-price'>"
            f"{peso(price)}"
            f"<small> / {period}</small>"
            f"</p>",
            unsafe_allow_html=True,
        )

        savings = (
            monthly * 12
            - yearly
        )

        if (
            billing_cycle == "Yearly"
            and yearly > 0
            and savings > 0
        ):

            st.markdown(
                f"<p class='ls-plan-savings'>"
                f"You save {peso(savings)} "
                "compared with paying monthly."
                f"</p>",
                unsafe_allow_html=True,
            )

        st.markdown(
            limits_html(subscription),
            unsafe_allow_html=True,
        )

    note(
        "Your subscription will be activated once the "
        "LungSight team approves this application."
    )

    if nav_buttons(
        "subscription",
        1,
    ):
        go_to_step(3)


# ============================================================
# STEP 4 - HOSPITAL ADMINISTRATOR
# ============================================================

def render_hospital_administrator():

    step_header(
        "Hospital administrator",
        "The person who will manage the LungSight account for the hospital.",
        required=True,
    )

    errors = st.container()

    data = (
        st.session_state
        .client_application["administrator"]
    )

    with st.form(
        "hospital_administrator_form"
    ):

        (
            first_name,
            middle_name,
            last_name,
        ) = name_fields(data)

        email_col, contact_col = st.columns(2)

        email = email_col.text_input(
            "Administrator email *",
            value=data.get(
                "email",
                "",
            ),
            placeholder="admin@hospital.org",
        )

        contact_number = contact_col.text_input(
            "Contact number *",
            value=data.get(
                "contact_number",
                "",
            ),
            placeholder="+63 9XX XXX XXXX",
        )

        st.caption(
            "This email will be used to create the hospital administrator account."
        )

        back, go_next = form_nav_buttons()

    if back:
        go_to_step(2)

    if not go_next:
        return

    missing = find_missing(
        {
            "First name": first_name,
            "Last name": last_name,
            "Administrator email": email,
            "Contact number": contact_number,
        }
    )

    if missing:

        errors.error(
            "Please complete: "
            + ", ".join(missing)
            + "."
        )

        return

    email = (
        email
        .strip()
        .lower()
    )

    if not is_valid_email(email):

        errors.error(
            "Please enter a valid email address."
        )

        return

    try:

        email_exists = auth_email_exists(
            email
        )

    except Exception as e:

        errors.error(
            f"Unable to verify the administrator email: {e}"
        )

        return

    if email_exists:

        errors.error(
            "This administrator email already exists in the system."
        )

        return

    st.session_state.client_application[
        "administrator"
    ] = {
        "first_name": first_name.strip(),
        "middle_name": middle_name.strip(),
        "last_name": last_name.strip(),
        "email": email,
        "contact_number": contact_number.strip(),
    }

    go_to_step(4)


# ============================================================
# STEP 5 - AGREEMENT
# ============================================================

def render_agreement():

    step_header(
        "Service agreement",
        "Please read and acknowledge the LungSight terms of service.",
    )

    with st.container(
        height=240,
        border=True,
    ):
        st.markdown(
            AGREEMENT_TEXT
        )

    agreed = st.checkbox(
        "I have read and agree to the LungSight Service Agreement.",
        value=(
            st.session_state
            .client_application["agreement"]
            .get("agreed", False)
        ),
    )

    errors = st.container()

    if nav_buttons(
        "agreement",
        3,
    ):

        if not agreed:

            errors.error(
                "You must agree to the service agreement "
                "before continuing."
            )

            return

        st.session_state.client_application[
            "agreement"
        ] = {
            "agreed": True
        }

        go_to_step(5)


# ============================================================
# STEP 6 - REVIEW & SUBMIT
# ============================================================

def show_review_section(
    key,
    title,
    rows,
    edit_step,
):
    """
    One review section with an Edit button.
    """

    with st.container(
        key=f"section_{key}"
    ):

        title_col, edit_col = st.columns(
            [5, 1],
            vertical_alignment="center",
        )

        title_col.markdown(
            f"<p class='ls-review-title'>"
            f"{title}"
            f"</p>",
            unsafe_allow_html=True,
        )

        if edit_col.button(
            "Edit",
            key=f"edit_{key}",
            width="stretch",
        ):
            go_to_step(edit_step)

        st.markdown(
            rows_html(rows),
            unsafe_allow_html=True,
        )


def render_review_submit():

    step_header(
        "Review application",
        "Check the details below. Use Edit to change anything before payment.",
    )

    application = (
        st.session_state.client_application
    )

    hospital = application["hospital"]
    representative = application["representative"]
    subscription = application["subscription"]
    administrator = application["administrator"]

    agreed = (
        application["agreement"]
        .get("agreed")
    )

    with st.container(
        height=360,
        border=False,
    ):

        hospital_rows = [
            (
                "Hospital name",
                hospital.get(
                    "hospital_name"
                ),
            ),
            (
                "Type",
                hospital.get(
                    "hospital_type"
                ),
            ),
            (
                "Address",
                hospital.get(
                    "address"
                ),
            ),
            (
                "Contact number",
                hospital.get(
                    "contact_number"
                ),
            ),
            (
                "Email",
                hospital.get(
                    "hospital_email"
                ),
            ),
        ]

        if hospital.get("website"):

            hospital_rows.append(
                (
                    "Website",
                    hospital.get(
                        "website"
                    ),
                )
            )

        show_review_section(
            "hospital",
            "Hospital information",
            hospital_rows,
            edit_step=0,
        )

        show_review_section(
            "representative",
            "Authorized representative",
            [
                (
                    "Name",
                    full_name(
                        representative
                    ),
                ),
                (
                    "Position",
                    representative.get(
                        "position"
                    ),
                ),
                (
                    "Contact number",
                    representative.get(
                        "contact_number"
                    ),
                ),
                (
                    "Email",
                    representative.get(
                        "email"
                    ),
                ),
            ],
            edit_step=1,
        )

        show_review_section(
            "plan",
            "Subscription",
            [
                (
                    "Plan",
                    subscription.get(
                        "plan_name"
                    ),
                ),
                (
                    "Billing cycle",
                    subscription.get(
                        "billing_cycle",
                        "Monthly",
                    ),
                ),
                (
                    "Amount due",
                    peso(
                        get_amount(
                            subscription
                        )
                    ),
                ),
            ],
            edit_step=2,
        )

        show_review_section(
            "administrator",
            "Hospital administrator",
            [
                (
                    "Name",
                    full_name(
                        administrator
                    ),
                ),
                (
                    "Email",
                    administrator.get(
                        "email"
                    ),
                ),
                (
                    "Contact number",
                    administrator.get(
                        "contact_number"
                    ),
                ),
            ],
            edit_step=3,
        )

        show_review_section(
            "agreement",
            "Service agreement",
            [
                (
                    "Status",
                    "Accepted"
                    if agreed
                    else "Not accepted",
                ),
            ],
            edit_step=4,
        )

    if nav_buttons(
        "review",
        4,
        "Continue to payment",
    ):
        go_to_step(6)


# ============================================================
# STEP 7 - PAYMENT
# ============================================================

def save_application():
    """
    Save the application as an unpaid draft.

    Returns the application ID or None.
    """

    application = (
        st.session_state.client_application
    )

    hospital = application["hospital"]
    representative = application["representative"]
    subscription = application["subscription"]
    administrator = application["administrator"]
    agreement = application["agreement"]

    result = create_hospital_application(
        hospital_name=hospital.get(
            "hospital_name"
        ),
        hospital_type=hospital.get(
            "hospital_type"
        ),
        hospital_address=hospital.get(
            "address"
        ),
        hospital_contact_number=hospital.get(
            "contact_number"
        ),
        hospital_email=hospital.get(
            "hospital_email"
        ),
        hospital_website=hospital.get(
            "website"
        ),
        applicant_first_name=representative.get(
            "first_name"
        ),
        applicant_middle_name=representative.get(
            "middle_name"
        ),
        applicant_last_name=representative.get(
            "last_name"
        ),
        applicant_email=representative.get(
            "email"
        ),
        applicant_contact_number=representative.get(
            "contact_number"
        ),
        applicant_position=representative.get(
            "position"
        ),
        selected_plan_id=subscription.get(
            "plan_id"
        ),
        billing_cycle=subscription.get(
            "billing_cycle",
            "Monthly",
        ),
        admin_first_name=administrator.get(
            "first_name"
        ),
        admin_middle_name=administrator.get(
            "middle_name"
        ),
        admin_last_name=administrator.get(
            "last_name"
        ),
        admin_email=administrator.get(
            "email"
        ),
        admin_contact_number=administrator.get(
            "contact_number"
        ),
        agreement_accepted=agreement.get(
            "agreed",
            False,
        ),
        application_status="Draft",
        payment_status="unpaid",
    )

    if not result.get("success"):

        st.error(
            result.get(
                "message",
                "Failed to create application.",
            )
        )

        return None

    return result["application_id"]


def start_checkout():
    """
    Create the application and then
    create the PayMongo checkout session.
    """

    from backend.payments import (
        create_checkout_session
    )

    application_id = (
        st.session_state.get(
            "application_id"
        )
    )

    if not application_id:

        with st.spinner(
            "Preparing your application..."
        ):

            application_id = (
                save_application()
            )

        if not application_id:
            return

        st.session_state.application_id = (
            application_id
        )

    with st.spinner(
        "Creating checkout session..."
    ):

        result = create_checkout_session(
            application_id
        )

    if not result.get("success"):

        st.error(
            result.get(
                "message",
                "Failed to create checkout session.",
            )
        )

        return

    st.session_state.checkout_url = (
        result["checkout_url"]
    )

    st.rerun()


def show_checkout(
    application_id,
    checkout_url,
):

    from backend.payments import (
        get_payment_status
    )

    note(
        "Checkout is ready. Complete your payment in "
        "the new tab, then come back here and refresh "
        "the status. Your application is submitted once "
        "PayMongo confirms the payment.",
        kind="success",
    )

    link_col, refresh_col = st.columns(2)

    link_col.link_button(
        "Open PayMongo checkout",
        checkout_url,
        type="primary",
        width="stretch",
    )

    if refresh_col.button(
        "Refresh status",
        key="refresh_payment_status",
        width="stretch",
    ):

        status = get_payment_status(
            application_id
        )

        if status.get("paid"):

            st.session_state.payment_success = (
                True
            )

            st.rerun()

        else:

            st.warning(
                f"Payment status: "
                f"{status.get('status')}. "
                "Please wait a moment and try again."
            )


def render_payment_step():

    step_header(
        "Payment",
        "Pay securely through PayMongo to submit your application.",
    )

    application = (
        st.session_state.client_application
    )

    subscription = (
        application["subscription"]
    )

    amount = get_amount(
        subscription
    )

    application_id = (
        st.session_state.get(
            "application_id"
        )
    )

    checkout_url = (
        st.session_state.get(
            "checkout_url"
        )
    )

    with st.container(
        key="payment_summary"
    ):

        st.markdown(
            rows_html(
                [
                    (
                        "Hospital",
                        application["hospital"].get(
                            "hospital_name"
                        ),
                    ),
                    (
                        "Plan",
                        subscription.get(
                            "plan_name"
                        ),
                    ),
                    (
                        "Billing cycle",
                        subscription.get(
                            "billing_cycle",
                            "Monthly",
                        ),
                    ),
                ]
            )
            + (
                f"<div class='ls-total'>"
                f"<span>Amount due</span>"
                f"<b>{peso(amount)}</b>"
                f"</div>"
            ),
            unsafe_allow_html=True,
        )

    if checkout_url:

        show_checkout(
            application_id,
            checkout_url,
        )

        return

    pay_label = (
        f"Pay {peso(amount)} with PayMongo"
    )

    if application_id:

        pay_clicked = st.button(
            pay_label,
            key="start_checkout",
            type="primary",
            width="stretch",
        )

    else:

        pay_clicked = nav_buttons(
            "payment",
            5,
            pay_label,
        )

    if pay_clicked:
        start_checkout()


# ============================================================
# AFTER PAYMENT
# ============================================================

def render_payment_success():

    st.success(
        "Application submitted — payment received."
    )

    st.markdown(
        """
        **What happens next?**

        1. Your application is now in the review queue.
        2. The LungSight team will verify your hospital details.
        3. Once approved, an invitation will be sent to the
           hospital administrator's email address.
        4. The administrator clicks the link, sets a password,
           and can start using LungSight.
        """
    )

    if st.button(
        "Close",
        key="success_close",
        width="stretch",
    ):

        clear_application()
        st.rerun()


def render_application_submitted():

    st.success(
        "Application submitted successfully."
    )

    st.markdown(
        """
        **What happens next?**

        Your hospital application will be reviewed by the
        LungSight system administrator. Once approved:

        1. Your hospital record will be created.
        2. The selected subscription will be assigned.
        3. The hospital administrator account will be created.
        4. Login credentials will be sent to the administrator's
           registered email address.
        """
    )

    if st.button(
        "Close",
        key="submitted_close",
        width="stretch",
    ):

        clear_application()
        st.rerun()


# ============================================================
# THE DIALOG
# ============================================================

STEP_RENDERERS = [
    render_hospital_information,
    render_authorized_representative,
    render_subscription_confirmation,
    render_hospital_administrator,
    render_agreement,
    render_review_submit,
    render_payment_step,
]


@st.dialog(
    "LungSight Hospital Application",
    width="medium",
)
def application_dialog(plan):

    initialize_application(plan)

    with st.container(
        key="application"
    ):

        # ----------------------------------------------------
        # PAYMENT SUCCESS
        # ----------------------------------------------------

        if st.session_state.get(
            "payment_success",
            False,
        ):

            render_payment_success()
            return


        # ----------------------------------------------------
        # APPLICATION SUBMITTED
        # ----------------------------------------------------

        if st.session_state.get(
            "application_submitted",
            False,
        ):

            render_application_submitted()
            return


        # ----------------------------------------------------
        # TWO-PAGE LUNGSIGHT INTRODUCTION
        # ----------------------------------------------------

        if render_application_introduction():
            return


        # ----------------------------------------------------
        # NORMAL APPLICATION
        # ----------------------------------------------------

        render_progress()

        current_step = (
            st.session_state.client_application_step
        )

        STEP_RENDERERS[
            current_step
        ]()


def show_client_application(plan):
    """
    Call this from the login page.

    Loads the application CSS and opens
    the LungSight hospital application dialog.
    """

    load_application_css()

    application_dialog(plan)